spring:
  datasource:
    url: jdbc:postgresql://142.93.74.100:5432/postgres?currentSchema=buildman
    username: postgres
    password: Doncella18
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
