spring:
  datasource:
    url: jdbc:h2:mem:builman
    username: sa
    password: sa
    driverClassName: org.h2.Driver
    data: classpath:sql/data.sql
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true